name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.6
        id: go
      - name: Build project
        run: |
          go build -v -o packer-builder-lightsail .
          go get github.com/mitchellh/gox
          $GOPATH/bin/gox -os="linux darwin windows" -arch="386 amd64" -output="packer-builder-lightsal-{{.OS}}-{{
          .Arch}}"
          tar -czvf packer-builder-lightsail.tar.gz ./packer-builder-lightsail*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          allowUpdates: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./packer-builder-lightsail.tar.gz
          asset_name: packer-builder-lightsail.tar.gz
          asset_content_type: application/tar